rework the tests, add an import test, test on python version 7 and 8 …
Devoxin/ksoftapi.py pull request #2
Opened 2020-02-24 16:37 UTC by TAG-Epic

…aswell

2020-03-05 08:30 UTC, TAG-Epic commented
Any update on this?

2020-03-07 14:32 UTC, devoxin requested changes

2020-03-07 14:32 UTC, Devoxin commented on run_tests.py
> +        formatted_test_name = f"-- {test_name[5:]} test --"
Single quotes

2020-03-07 14:32 UTC, Devoxin commented on run_tests.py
> +            print("Failed")
Single quotes

2020-03-07 14:32 UTC, Devoxin commented on run_tests.py
> +            print("Passed")
Single quotes

2020-03-07 14:32 UTC, Devoxin commented on run_tests.py
> +    print(f"Fails: {fail_count}")
Single quotes

2020-03-07 14:32 UTC, Devoxin commented on run_tests.py
> +    sys.exit(fail_count)
`0` if success, `1` if any failed.

2020-03-23 09:48 UTC, TAG-Epic commented
Done!

2020-03-23 10:15 UTC, merged